### ISSUE TITLE
Is the API still working?

### ISSUE THREAD

**Issue by erikmd** [goulinkh/rooms-finder#12]
Bonjour @goulinkh,

Je viens d'essayer d'utiliser https://rooms-finder.goulin.fr/ mais j'ai l'impression que le calcul des créneaux dispos renvoie toujours invariablement : `7:45 AM jusqu'à 8:00 PM`.

Du coup je soupçonne que l'API de CELCAT a évolué et nécessiterait des changements… dans ce cas aurais-tu le temps et le souhait de mettre à jour rooms-finder ?

* Si oui, deux mini-suggestions (mais c'est vrai que j'aurais pu aussi ouvrir 2 issues différentes) :
  * ça serait bien qu'en cliquant sur le bouton `Chercher`, les 3 listes déroulantes ne soient pas effacées (pour tester rapidement plusieurs combinaisons similaires)
  * il manque a priori le nouveau bâtiment `U6` dans la 2e liste déroulante (ce qui est sans doute lié au changement d'API ? à moins que les noms des bâtiments à afficher soient codés en dur :)

* Sinon pas de souci ! peut-être que l'Université mettra prochainement une fonctionnalité similaire à rooms-finder à disposition… (mais ce n'est pas encore le cas à ma connaissance)

**Comment by erikmd** [comment]
Au fait, je viens de voir que [l'appli Android](https://github.com/axellaffite/ut3_calendar) d'@axellaffite utilise aussi ton API REST;
du coup une mise à jour de rooms-finder serait bénéfique aussi pour les utilisateurs de l'appli… (si je ne dis pas de bêtises et qu'Axel utilise aussi l'instance que tu héberges @goulinkh :)

**Comment by goulinkh** [comment]
Bonjour M. Erik,

>Je viens d'essayer d'utiliser https://rooms-finder.goulin.fr/ mais j'ai l'impression que le calcul des créneaux dispos renvoie toujours invariablement : 7:45 AM jusqu'à 8:00 PM.

Effectivement l'API de CELCAT n'est pas changé, mais il fallait redemarrer le serveur de rooms-finder afin de récuperer les emplois du temps de cette année.


> ça serait bien qu'en cliquant sur le bouton Chercher, les 3 listes déroulantes ne soient pas effacées (pour tester rapidement plusieurs combinaisons similaires)

C'est fait.

Cordialement

**Comment by erikmd** [comment]
Excellent ! merci beaucoup Goulin :-)
