### ISSUE TITLE
Exactitude des informations

### ISSUE THREAD

**Issue by BENICHN** [goulinkh/rooms-finder#14]
Rebonjour, après le problème des amphis qui est maintenant réglé, j'en profite pour mentionner aussi un dernier problème, peut être plus rapide à régler celui-là. Je trouve que les horaires affichées ne sont pas très accurate, j'entends par là que souvent, des salles marquées non libres le sont, et inversement. peut être est-ce à cause de mises à jour trop peu fréquentes de celcat.

**Comment by goulinkh** [comment]
Les données sont rafraîchi chaque 2 heures, j'évite de faire des délais plus courts afin d'éviter de spammer le serveur de la fac.
