### ISSUE TITLE
Résultats depuis la rentrée 2022 ?

### ISSUE THREAD

**Issue by BChaluleau** [goulinkh/rooms-finder#16]
Bonjour @goulinkh,
Déjà merci beaucoup pour votre travail, https://rooms-finder.goulin.fr/ est vraiment un excellent service, qui remplit un vrai manque au quotidien sur le campus.

Depuis la rentrée, je suis orphelin, les résultats retournés ne me semblent pas cohérents (toutes les salles semblent disponibles, de 7h45 à 20h (ce qui me semble peu crédible).

Je comprendrais tout à fait que vous n'ayez ni le temps ni l'envie de continuer à maintenir le site, mais si jamais le geste à effectuer pour rétablir le service n'était pas trop lourd, vous feriez des heureux ! 

Merci encore pour votre travail

**Comment by goulinkh** [comment]
Bonjour, j'ai vu que cette année l'EDT a changé et qu'il faut se connecter afin d'avoir access à l'emploit du temps, j'espère que la méthode que j'utilisais les années precedantes reste fonctionnelle, si c'est le cas je ferrai une mise à jour au site afin de chercher les informations de cette année sinon je vais devoir arrêter le site malheureusement comme je ne m'en sers plus et je n'aurai pas assez de motivation pour chercher une nouvelle stratégie.

**Comment by goulinkh** [comment]
Finalement cela a marché! Apparemment EDT a le même comportement qu'avant :smile:

**Comment by bollombollom** [comment]
Merci beaucoup pour votre travail, c'est très (très) sympa !

**Comment by erikmd** [comment]
Merci beaucoup @goulinkh 👍👍

pour info, cette fonctionnalité apportée par ton API web est toujours super utile pour les étudiants et enseignants !, y compris l'application Android d'@axellaffite [`com.edt.ut3`](https://github.com/axellaffite/ut3_calendar) (qui intègre ton API :)

Mais bien entendu maintenant que vous avez tous les deux soutenu votre diplôme de Master, il est normal que vous puissiez vouloir transmettre le flambeau à d'autres nouveaux mainteneurs (e.g., étudiants de M1/M2 SDL).

→ On en a discuté avec @fmigeon, @elavinal et @axellaffite ces derniers mois et pour résumer :

- Axel et moi allons essayer d'encadrer un projet de M1 SDL autour d'évolutions de l'appli `com.edt.ut3`
- Quant à l'hébergement du service web rooms-finder, qui pourrait générer un coût de ton côté jusque-là, on pourra aussi louer une VM dédiée, que le(s) nouveau(x) mainteneur(s) et moi administreraient.
